StreamBasedNotifs/StreamBasedNotifs/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('capture.urls', namespace='capture')),
]

StreamBasedNotifs/capture/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import captureEvents

urlpatterns = [
    url(r'^',captureEvents,name="capturer"),
]

StreamBasedNotifs/capture/models.py
from django.db import models
# Create your models here.


class Stream(models.Model):
    '''for saving new streams'''
    name = models.CharField(max_length=255)
    user_type = models.CharField(max_length=255, blank=True)
    user_id = models.CharField(max_length=255, blank=True)
    associated_user_ids = models.TextField(blank=True) #List of string array stored as a comma separated text
    timestamp = models.IntegerField(default=0)
    info = models.TextField() # List of tuples eg.: name : <string> stored as comma separated  text
    def __unicode__(self):
        return self.name


class Notification(models.Model):
    '''saving notifications'''
    name = models.CharField(max_length=255)
    event_name = models.CharField(max_length=255)
    target = models.BooleanField(default=False) #if false user , else assoc. user
    delay = models.IntegerField(default=0)
    url =  models.TextField()
    no_delay = models.BooleanField(default=False)
    def __unicode__(self):
        return  self.name

StreamBasedNotifs/capture/forms.py
from django import forms
from .models import Stream


class NotificationForm(forms.Form):
    name = forms.CharField(required=True, label="Notification Name ")
    event = forms.ChoiceField(widget=forms.Select(attrs={'class': 'select-style'}), required=True,
                              label="Event Name ")
    target = forms.ChoiceField(required=True, choices=[(0, "User"), (1, "Associated User")],
                               widget=forms.Select(attrs={'class': 'select-style'}), label="Target ")
    delay = forms.IntegerField(required=False, label="Delay ")
    no_delay = forms.BooleanField(label="No Delay", required=False)
    url = forms.URLField(label="Webhook URL ", required=True)
    def __init__(self, *args, **kwargs):
        '''In order to update dropdown for new coming events '''
        super(NotificationForm, self).__init__(*args, **kwargs)
        choices = []
        events = Stream.objects.filter()
        for event in events:
            choices.append((event.name, event.name))
        self.fields['event'].choices = choices

StreamBasedNotifs/capture/views.py
from django.shortcuts import render
from django.views.decorators.csrf import  csrf_exempt #for csrf protection
from .models import Stream , Notification
from .forms import NotificationForm
from django.http import JsonResponse
# Create your views here.

@csrf_exempt
def captureEvents(request):
    '''Route to background task and display the main page'''
    streams = Stream.objects.all()
    events = {}
    for stream in streams:
        events[stream.name] = stream.info.split(',')
    form = NotificationForm(request.POST or None)
    if form.is_valid() :
        notification_name = form.cleaned_data.get("name")
        event_name = form.cleaned_data.get("event")
        target = form.cleaned_data.get("target") #if 0 user if 1 assoc. user
        no_delay = form.cleaned_data.get("no_delay")
        if not no_delay:
            delay = form.cleaned_data.get("delay")
        url = form.cleaned_data.get("url")
        print no_delay
        if Notification.objects.filter(event_name=event_name) :
            '''If there is a notification that created for this event update it'''
            notification = Notification.objects.get(event_name=event_name)
            notification.name = notification_name
            if not no_delay :
                notification.delay = delay
            notification.url = url
            notification.no_delay = no_delay
            if target == '0':
                notification.target = False
            else:
                notification.target = True
            #notification.target = (target =='0') ? False  : True
            notification.save()
        else:
            '''If there is no notification created for this event'''
            itarget = False
            if target == '1':
                itarget = True
            if not no_delay:
                Notification.objects.create(event_name=event_name, name=notification_name,
                                        delay=delay, url=url, target=itarget)
            else :
                Notification.objects.create(event_name=event_name, name=notification_name,
                                            no_delay=no_delay, url=url, target=itarget)
        return render(request, "updateCapture.html", {"events": events, "form": NotificationForm()})
    return render(request, "updateCapture.html", {"events": events, "form": form})


def updateEvents(request):
    if request.method == "GET" :
        events = {}
        streams = Stream.objects.all()
        for stream in streams:
            events[stream.name] = stream.info.split(',')
        return JsonResponse(events)
    return JsonResponse({})

StreamBasedNotifs/templates/capture.html
<html>
  <head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
      <script type="text/javascript">
            {% block update %}{% endblock %}
      </script>
      <script type="text/javascript">
         {% block delay %}{% endblock %}
      </script>
  </head>

  <h1 style="margin:1em 0em 0em 30%;">Stream Based Notifications</h1>


  <div class="row" style="margin:3% 0% 10% 10%;">
    <div class="col-md-6">
      <h2 style="margin:0px 0em 6% 5%;text-decoration: underline;">Events</h2>
      <ul id="events">
      {% for name, info in events.items %}
        <li>{{name}}</li>
        <ul>
          {% for i in info %}
            <li>{{i}}</li>
          {% endfor %}
        </ul>
      {% endfor %}
      </ul>
    </div>

    <div class="col-md-6">
      <h2 style="margin:0px 0em 1em 2em;text-decoration: underline;">Notification</h2>
      <form action="" method="post" class="form-horizontal" id="form">
        {{form.as_ul}}
        <input type="submit" value="Send" id="send_button">
      </form>
    </div>
  </div>
</html>

StreamBasedNotifs/templates/updateCapture.html
{% extends "capture.html" %}
{% block update %}
    var socket = new WebSocket('ws://' + window.location.host + '/stream/');

        socket.onopen = function open() {
          alert('WebSockets connection created.');
        };
        socket.onmessage = function message(event) {
          var data = JSON.parse(event.data);
          // NOTE: We escape JavaScript to prevent XSS attacks.
          var event_name = data["event_name"];
          var blueprint = data["blueprint"];
          var bluelist = blueprint.split(",");
          var events = $("#events");
          events.append("<li>"+event_name+"</li><ul>");
          bluelist.forEach(function(each){
             events.append("<li>" + each + "</li>");
          });
          events.append("</ul>");
        };
        if (socket.readyState == WebSocket.OPEN) {
          socket.onopen();
        }
{% endblock %}

{% block delay %}
    $(document).ready(function() {

        $('#id_no_delay').change(function() {
            if($(this).is(":checked")) {
                $("#id_delay").attr("disabled", "disabled");
            }else{
                $("#id_delay").removeAttr("disabled");
            }
        });
        $('#send_button').click(function(){
            var formValidated = true;
            if($('#id_no_delay').prop('checked') == false){
                $('#id_delay').each(function(){
                    if($(this).val() === '') {
                        alert('Please check to checkbox or fill the field');
                        formValidated = false ;
                    }
                });
            }
            $('#form').submit(formValidated);
        });
    });
{% endblock %}